# Generated by Django 4.2.10 on 2024-03-06 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0003_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='image',
            field=models.ImageField(default='placeholder.png', null=True, upload_to='images'),
        ),
    ]
